### ISSUE TITLE
Write exercise 6 common elements in python

### ISSUE THREAD

**Issue by bdharris08** [bdharris08/Gym-Time#4]
write it in python with unit tests (see test.py)
- two files: "common_elements.py" and "common_elements_test.py"

**Comment by bdharris08** [comment]
@rmcavin this is really similar to your leaflet-practice

**Comment by Detonavomek** [comment]
Are you talk about implementing sorting from https://github.com/bdharris08/Gym-Time/blob/master/exercises.txt ?

**Comment by bdharris08** [comment]
@Detonavomek I mean the common elements question on the main readme. You are welcome to fork and practice on any of them. And feel free to PR for hacktoberfest. However, I will soon take all the implementations out so that people can fork for their own practice, and for that goal we will need unit tests for each exercise. If you are interested in writing some of those tests for your favorite language, I will make an issue an label it Hacktoberfest
